// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/alerts" | "/analytics" | "/anonymous-reports" | "/briefings" | "/briefings/[id]" | "/cases" | "/cases/[id]" | "/contacts" | "/contacts/[id]" | "/daily-log" | "/daily-log/[id]" | "/daily-log/new" | "/dashboard" | "/dispatch" | "/incidents" | "/incidents/[id]" | "/incidents/new" | "/login" | "/lost-found" | "/lost-found/[id]" | "/notifications" | "/patrons" | "/patrons/[id]" | "/personnel" | "/personnel/[id]" | "/reports" | "/reports/[type]" | "/settings" | "/settings/dropdowns" | "/settings/form-templates" | "/settings/integrations" | "/settings/locations" | "/settings/notification-rules" | "/settings/organization" | "/settings/properties" | "/settings/roles" | "/settings/users" | "/vehicles" | "/vehicles/[id]" | "/visitors" | "/visitors/[id]" | "/work-orders" | "/work-orders/[id]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/alerts": {}
  "/analytics": {}
  "/anonymous-reports": {}
  "/briefings": {}
  "/briefings/[id]": { "id": string; }
  "/cases": {}
  "/cases/[id]": { "id": string; }
  "/contacts": {}
  "/contacts/[id]": { "id": string; }
  "/daily-log": {}
  "/daily-log/[id]": { "id": string; }
  "/daily-log/new": {}
  "/dashboard": {}
  "/dispatch": {}
  "/incidents": {}
  "/incidents/[id]": { "id": string; }
  "/incidents/new": {}
  "/login": {}
  "/lost-found": {}
  "/lost-found/[id]": { "id": string; }
  "/notifications": {}
  "/patrons": {}
  "/patrons/[id]": { "id": string; }
  "/personnel": {}
  "/personnel/[id]": { "id": string; }
  "/reports": {}
  "/reports/[type]": { "type": string; }
  "/settings": {}
  "/settings/dropdowns": {}
  "/settings/form-templates": {}
  "/settings/integrations": {}
  "/settings/locations": {}
  "/settings/notification-rules": {}
  "/settings/organization": {}
  "/settings/properties": {}
  "/settings/roles": {}
  "/settings/users": {}
  "/vehicles": {}
  "/vehicles/[id]": { "id": string; }
  "/visitors": {}
  "/visitors/[id]": { "id": string; }
  "/work-orders": {}
  "/work-orders/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
