// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/(auth)/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/alerts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/alerts">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/alerts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/anonymous-reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/anonymous-reports">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/anonymous-reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/briefings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/briefings/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/briefings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/briefings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/briefings">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/briefings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/cases/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cases/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/cases/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/cases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/cases">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/cases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/contacts/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contacts/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/contacts/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/contacts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contacts">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/contacts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/daily-log/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/daily-log/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/daily-log/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/daily-log/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/daily-log/new">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/daily-log/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/daily-log/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/daily-log">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/daily-log/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/dispatch/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dispatch">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/dispatch/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/incidents/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/incidents/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/incidents/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/incidents/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/incidents/new">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/incidents/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/incidents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/incidents">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/incidents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/lost-found/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lost-found/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/lost-found/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/lost-found/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/lost-found">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/lost-found/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/patrons/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patrons/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/patrons/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/patrons/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/patrons">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/patrons/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/personnel/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/personnel/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/personnel/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/personnel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/personnel">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/personnel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/reports/[type]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports/[type]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/reports/[type]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reports">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/dropdowns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/dropdowns">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/dropdowns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/form-templates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/form-templates">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/form-templates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/integrations">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/locations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/locations">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/locations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/notification-rules/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/notification-rules">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/notification-rules/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/organization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/organization">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/organization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/properties/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/properties">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/properties/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/roles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/roles">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/roles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/settings/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings/users">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/settings/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/vehicles/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vehicles/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/vehicles/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/vehicles/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vehicles">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/vehicles/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/visitors/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/visitors/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/visitors/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/visitors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/visitors">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/visitors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/work-orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/work-orders/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/work-orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/work-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/work-orders">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/work-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/(auth)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(auth)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
